# <center>__Assignment 1__</center>

__Directions__: Do this assignment in Jupyter Notebook and provide screenshots of code and output in this word document wherever required. You will upload this word document containing screenshots of code and answers as well as your Jupyter Notebook to Canvas. All assignments will be submitted and graded through canvas and grades will be transferred to the 2U platform. 

__Goal__: : The goal of this assignment is to give you the opportunity to practice some key aspects of data preprocessing, which is a crucial step the data science workflow.

__Packages__: Core packages required for this assignment are numpy, pandas and sklearn. You can import additional packages if necessary, but these mentioned packages should be enough.

__Points__: 50

In [1]:
"""import the required packages"""
import numpy as np
import pandas as pd
import re
from sklearn.preprocessing import LabelBinarizer, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

## Question 1

a) Read the boston dataset csv files provided for this assignment into Python (you can use pd.read_csv()). The boston datasets are boston_weather_1, boston_weather_2, boston_weather_3, boston_weather_4, and more_weather_variables, then assign the datasets to a DataFrame variable called boston_1, boston_2, boston_3, boston_4, and more_variables, respectively. Combine or concatenate the DataFrames, boston_1, boston_2, boston_3, and boston_4 and assign the results to a DataFrame called combined_boston. These four datasets should be combined vertically since they have the same variable names, such that boston_1 is stacked on top of boston_2, and the result is stacked on top of boston_3, and the result is further stacked on top of boston_4. Horizontally merge, join or concatenate the combined_boston and more_variables DataFrames and assign the results to a DataFrame called boston_data. Print the first five rows of the boston_data, and the last five rows of the boston_data. Also print out the shape of the boston_data. 

In [2]:
"""read in the data"""
boston_1 = pd.read_csv('boston_weather_1.csv')
boston_2 = pd.read_csv('boston_weather_2.csv')
boston_3 = pd.read_csv('boston_weather_3.csv')
boston_4 = pd.read_csv('boston_weather_4.csv')
more_variables = pd.read_csv('more_weather_variables.csv')

In [3]:
"""concatenate the dataframes"""
combined_boston = pd.concat([boston_1, boston_2, boston_3, boston_4], ignore_index=True)

In [4]:
"""merge (inner join) combined_boston and more_variables on indices"""
boston_data = pd.merge(combined_boston, more_variables, how='inner',
                       left_index=True, right_index=True)

In [5]:
"""print boston_data head"""
boston_data.head(5)

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
0      1  1920     -8.0      48.0        37.0         12.0    12.5    29.5   
1      2  1920     -7.0      52.0        34.0         16.0    20.6    34.6   
2      3  1920     10.0      72.0        45.0         25.0    30.5    48.0   
3      4  1920     26.0      67.0        46.0         37.0    38.0    52.1   
4      5  1920     36.0      86.0        61.0         45.0    47.5    61.8   

   meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
0      21.0       2.72    24.8           0.74         6.7  
1      27.6       4.11    32.5           1.01        12.2  
2      39.3       3.72      11           1.15           6  
3      45.1       5.68       2           1.19           2  
4      54.6       5.26       0           3.23           0

In [6]:
"""print boston_data tail"""
boston_data.tail(5)

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
1135      8  2014     58.0      91.0        70.0         69.0    63.2    78.4   
1136      9  2014     46.0      93.0        72.0         56.0    58.3    74.2   
1137     10  2014     39.0      81.0        61.0         52.0    49.7    63.0   
1138     11  2014     23.0      66.0        48.0         34.0    35.5    49.5   
1139     12  2014     18.0      64.0        44.0         29.0    32.8    43.7   

      meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
1135      70.8       1.75       0           1.06           0  
1136      66.2       0.70       0           0.22           0  
1137      56.4       5.83       0           2.25           0  
1138      42.5       5.27     2.6           1.64         2.3  
1139      38.3       6.56     0.3           2.90         0.3

In [7]:
"""print boston_data shape"""
boston_data.shape

(1140, 13)

b) Check the boston_data to verify how many missing data points exist under each column. 

In [8]:
"""check for null values in each column"""
boston_data.isnull().sum()

Month            0
Year             0
LowTemp          6
HighTemp         5
WarmestMin       6
ColdestHigh      9
AveMin           3
AveMax           6
meanTemp         0
TotPrecip        0
TotSnow          0
Max24hrPrecip    0
Max24hrSnow      0
dtype: int64

c) Drop the rows or instances that contain any missing data. Assign the resulting DataFrame to a variable called clean_boston_data. Note that this is only one way of dealing with missing data and cases with missing data are usually used if you have sufficient sample size. Check for missing data again to ensure there is no missing data in the clean_boston_data. Print the shape of the clean_boston_data.

In [9]:
"""
drop na from boston_data and assign to a new dataframe clean_boston_data.
check for na in clean_boston_data to ensure missing values have been handled.
"""
clean_boston_data = boston_data.dropna(axis=0)
clean_boston_data.isnull().sum()

Month            0
Year             0
LowTemp          0
HighTemp         0
WarmestMin       0
ColdestHigh      0
AveMin           0
AveMax           0
meanTemp         0
TotPrecip        0
TotSnow          0
Max24hrPrecip    0
Max24hrSnow      0
dtype: int64

In [10]:
"""print shape of clean_boston_data"""
clean_boston_data.shape

(1112, 13)

d) Format all the column names to lowercase and include underscore between column names that consist of two words. For example, meanTemp should become mean_temp, and Max24hrPrep can become max_24hr_prep, and HighTemp becomes high_temp, etc. Reassign the DataFrame with the formatted column names to the same variable, clean_boston_data. Print or output the columns of the clean_boston_data DataFrame. 

In [11]:
"""
convert clean_boston_data to snake case.
print column names to verify conversion
"""
pattern = re.compile(r'(?!^)(?=[A-Z])|(?=[0-9]{2})')
clean_boston_data = clean_boston_data.rename(columns=lambda x : pattern.sub('_', x).lower())
clean_boston_data.columns

Index(['month', 'year', 'low_temp', 'high_temp', 'warmest_min', 'coldest_high',
       'ave_min', 'ave_max', 'mean_temp', 'tot_precip', 'tot_snow',
       'max_24hr_precip', 'max_24hr_snow'],
      dtype='object')

e) Select or slice all data from the clean_boston_data DataFrame, except the data where the Year is 1930. You can call this subset data excluding_1930. Using the excluding_1930 DataFrame, output the first 20 unique values in the Year column.  

In [12]:
"""
filter clean_boston_data to remove records with year == 1930
print the first 20 unique values in the year column to verify dropping 1930
"""
excluding_1930 = clean_boston_data[clean_boston_data['year'] != 1930]
excluding_1930['year'].unique()[0:19]

array([1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939])

f) Select the data from the clean_boston_data where the Year is and 1995 AND the high_temp is greater than or equal to 90. Output or display the whole selected data. Here, you don’t have to assign it to any variable, but you could if you want to. 

In [13]:
"""
select appropriate records from clean_boston_data using
column conditions
"""
clean_boston_data[(clean_boston_data['year'] == 1995) &
                  (clean_boston_data['high_temp'] >= 90)]

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
905      6  1995      53.0       95.0         73.0          61.0     60.2   
906      7  1995      59.0      100.0         75.0          67.0     67.1   
907      8  1995      55.0       96.0         72.0          66.0     64.1   

     ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
905     77.0       68.6        1.55        0             0.53             0  
906     84.6       75.9        2.06        0             0.88             0  
907     81.5       72.8        0.82        0             0.63             0

g) Select the data from the clean_boston_data where the Year is and 1995 OR the high_temp is greater than 89. Output or print the first 20 rows of the selected data. Here, you don’t have to assign it to any variable, but you could if you want to. 

In [14]:
"""
select appropriate records from clean_boston_data using
column conditions
"""
clean_boston_data[(clean_boston_data['year'] == 1995) |
                  (clean_boston_data['high_temp'] > 89)].head(20)

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
6       7  1920      56.0       90.0         71.0          65.0     63.4   
7       8  1920      56.0       93.0         74.0          69.0     65.2   
16      5  1921      41.0       93.0         70.0          48.0     50.0   
19      8  1921      55.0       92.0         72.0          69.0     61.5   
20      9  1921      53.0       93.0         75.0          64.0     60.1   
29      6  1922      52.0       92.0         72.0          59.0     60.8   
30      7  1922      58.0       93.0         72.0          64.0     64.4   
31      8  1922      54.0       93.0         72.0          65.0     63.4   
41      6  1923      47.0       96.0         74.0          53.0     59.6   
42      7  1923      56.0       94.0         72.0          62.0     62.2   
43      8  1923      51.0       94.0         74.0          63.0     60.5   
53      6  1924      48.0       90.0         68.0          58.0     58.2   
54      7  1924      58.0       95.0         73.0          68.0     64.8   
55      8  1924      56.0       98.0         75.0          68.0     64.4   
56      9  1924      44.0       90.0         71.0          59.0     54.4   
65      6  1925      53.0      100.0         80.0          59.0     61.1   
66      7  1925      54.0       95.0         73.0          66.0     64.1   
67      8  1925      50.0       92.0         70.0          67.0     62.3   
68      9  1925      41.0       90.0         72.0          56.0     56.0   
78      7  1926      56.0      103.0         75.0          64.0     62.6   

    ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
6      81.4       72.4        1.56        0             0.76             0  
7      78.9       72.0        2.32        0             1.00             0  
16     66.1       58.0        3.63        0             1.82             0  
19     77.7       69.6        1.63        0             1.12             0  
20     76.9       68.5        1.22        0             0.36             0  
29     76.5       68.7        8.05        0             3.32             0  
30     79.7       72.0        2.63        0             0.86             0  
31     77.4       70.4        4.75        0             1.23             0  
41     79.0       69.3        2.03        0             1.02             0  
42     77.7       69.9        3.36        0             0.78             0  
43     78.1       69.3        2.07        0             0.78             0  
53     75.1       66.7        1.07        0             0.36             0  
54     82.9       73.8        2.04        0             0.70             0  
55     79.5       71.9        6.86        0             4.15             0  
56     70.0       62.2        6.96        0             3.89             0  
65     80.7       70.9        4.59        0             1.36             0  
66     80.5       72.3        3.54        0             1.19             0  
67     80.0       71.1        1.40        0             0.47             0  
68     72.1       64.1        3.45        0             1.46             0  
78     78.4       70.4        6.06        0             2.33             0

## Question 2

a) Read the student_data file provided into Python (take note of the file extension to use the appropriate pandas reader to read the data).  Drop the first empty column in Python and assign the DataFrame to a variable student_data.  

In [15]:
"""read in the data and check for missing column"""
student_data = pd.read_excel('student_data.xlsx')
student_data.head()

Unnamed: 0 ice_cream_flavor  math  reading  science 
0         NaN          vanilla    90       82        90
1         NaN      chocollate    100       73        92
2         NaN          vanilla    80       92        95
3         NaN      strawberry     95      100        82
4         NaN      strawberry     90       79        81

In [16]:
"""drop the first column"""
student_data.drop(columns=['Unnamed: 0'], inplace=True)
student_data.head()

ice_cream_flavor  math  reading  science 
0          vanilla    90       82        90
1      chocollate    100       73        92
2          vanilla    80       92        95
3      strawberry     95      100        82
4      strawberry     90       79        81

b) The student_data shows the different midterm scores of students in math, reading and science, and their favorite ice cream flavors. Select the data in the ice_cream_flavor column and convert the flavors to a numpy array, then assign it to a variable called flavor. From the student_data, select the math, reading and science scores all at once and convert the selected data to a numpy array and assign it to a variable called scores. Print the data in the flavor and scores arrays. 

In [17]:
"""create and print flavors array"""
flavor = np.array(student_data['ice_cream_flavor'])
flavor

array(['vanilla', 'chocollate ', 'vanilla', 'strawberry ', 'strawberry ',
       'chocollate ', 'vanilla', 'vanilla', 'chocollate ', 'chocollate ',
       'vanilla', 'strawberry ', 'strawberry ', 'chocollate ', 'vanilla',
       'vanilla'], dtype=object)

In [18]:
"""update chocollate to chocolate and trim whitespace from strawberry"""
conditions = [flavor == 'chocollate ', flavor == 'strawberry ',
              flavor == 'vanilla']
values = ['chocolate', 'strawberry', flavor]
flavor = np.select(conditions, values)
flavor

array(['vanilla', 'chocolate', 'vanilla', 'strawberry', 'strawberry',
       'chocolate', 'vanilla', 'vanilla', 'chocolate', 'chocolate',
       'vanilla', 'strawberry', 'strawberry', 'chocolate', 'vanilla',
       'vanilla'], dtype=object)

In [19]:
"column name science contains extra whitespace"
student_data.columns

Index(['ice_cream_flavor', 'math', 'reading', 'science '], dtype='object')

In [20]:
"""strip whitespace from column name "science" """
student_data = student_data.rename(columns=lambda x : x.strip())
student_data.columns

Index(['ice_cream_flavor', 'math', 'reading', 'science'], dtype='object')

In [21]:
"""create and print scores array"""
scores = np.array(student_data[['math', 'reading', 'science']])
scores

array([[ 90,  82,  90],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [ 90,  90,  90],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [ 86,  92,  90],
       [100,  89,  89],
       [ 83,  95,  79]])

c)	Use the scores and flavor arrays to slice out the scores where the flavor is chocolate only.

In [22]:
"""slice all scores where flavor == chocolate using boolean idx"""
chocolate_scores = scores[flavor == 'chocolate']
chocolate_scores

array([[100,  73,  92],
       [ 90,  90,  90],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 86,  92,  90]])

d) Use the scores and flavor arrays to slice out the scores where the flavor is chocolate OR vanilla.

In [23]:
"""slice all scores where flavor == chocolate or flavor == vanilla using boolean idx"""
chocolate_vanilla_scores = scores[flavor != 'strawberry']
chocolate_vanilla_scores

array([[ 90,  82,  90],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 90,  90,  90],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 86,  92,  90],
       [100,  89,  89],
       [ 83,  95,  79]])

e)	Use the scores and flavor arrays to slice out the scores where the flavor is not chocolate (you can use the “~ “sign). 

In [24]:
"""slice all scores where flavor != chocolate using boolean idx"""
no_chocolate_scores = scores[flavor != 'chocolate']
no_chocolate_scores

array([[ 90,  82,  90],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  89],
       [ 83,  95,  79]])

f)	Slice out all math and reading scores where the flavor is chocolate, then compute the mean of math and reading scores for this subset (you can use the .mean() method on the array and specify the axis parameter value appropriately). 

In [25]:
"""
select the math and reading scores where flavor == chocolate
print the mean scores for math and reading
"""
math_reading_chocolate = scores[:, 0:2][flavor == 'chocolate']
np.mean(math_reading_chocolate, axis=0)

array([92.2, 85.4])

## Question 3

Imagine that you wanted to use the student_data in question 2a to make predictions such that the ice_cream_flavor, math and reading columns are input variables and science column is the output variable you want to predict

a) Use the LabelBinarizer() in the sklearn package to transform the ice_cream_flavor column in the student_data to dummy variables, then join these dummy variables to the student_data and drop the original ice_cream_flavor column. Reassign the resulting DataFrame to a variable called student_data_1. Print out the entire student_data_1 DataFrame 

In [26]:
"""
apply sklearn LabelBinarizer to student_data ice_cream_flavor column
apppend one hot encoded variable to student_data and assin to a new variable student_data_one
"""
lb = LabelBinarizer()
encoded_flavor = lb.fit_transform(flavor)
encoded_flavor = pd.DataFrame(data=encoded_flavor,
                              columns=['chocolate', 'strawberry', 'vanilla'])
student_data_1 = pd.merge(student_data, encoded_flavor, how='inner', left_index=True,
                          right_index=True)
student_data_1.drop(columns=['ice_cream_flavor'], inplace=True)
student_data_1.head(student_data_1.shape[0])

math  reading  science  chocolate  strawberry  vanilla
0     90       82       90          0           0        1
1    100       73       92          1           0        0
2     80       92       95          0           0        1
3     95      100       82          0           1        0
4     90       79       81          0           1        0
5     90       90       90          1           0        0
6    100       89       91          0           0        1
7     80       85       79          0           0        1
8     85       99       85          1           0        0
9    100       73       92          1           0        0
10    80       92       95          0           0        1
11    95      100       82          0           1        0
12    90       79       81          0           1        0
13    86       92       90          1           0        0
14   100       89       89          0           0        1
15    83       95       79          0           0        1

b) Extract the math, reading and science scores and use the StandardScaler() class in the sklearn.preprocessing module to standardize these scores, then merge the standardized scores to the dummy variables, and call the resulting DataFrame student_data_std. Print out the entire student_data_1 DataFrame.

In [27]:
"""
apply sklearn StandardScaler to student scores (math, reading, science)
append to one hot encoded ice cream flavors and assign as dataframe to var student_data_std
"""
sc = StandardScaler()
student_data_std = student_data_1.copy()
student_data_std[['math', 'reading', 'science']] = sc.fit_transform(student_data_1[['math',
                                                                     'reading', 'science']])
student_data_std.head(student_data_std.shape[0])

math   reading   science  chocolate  strawberry  vanilla
0  -0.034524 -0.709277  0.536906          0           0        1
1   1.346430 -1.762225  0.902459          1           0        0
2  -1.415477  0.460665  1.450789          0           0        1
3   0.655953  1.396618 -0.925306          0           1        0
4  -0.034524 -1.060260 -1.108083          0           1        0
5  -0.034524  0.226676  0.536906          1           0        0
6   1.346430  0.109682  0.719683          0           0        1
7  -1.415477 -0.358295 -1.473636          0           0        1
8  -0.725001  1.279624 -0.376977          1           0        0
9   1.346430 -1.762225  0.902459          1           0        0
10 -1.415477  0.460665  1.450789          0           0        1
11  0.655953  1.396618 -0.925306          0           1        0
12 -0.034524 -1.060260 -1.108083          0           1        0
13 -0.586905  0.460665  0.536906          1           0        0
14  1.346430  0.109682  0.354130          0           0        1
15 -1.001191  0.811647 -1.473636          0           0        1

c) Using a split ratio of 70:30, spit the student_data_1 into training and test set. Reference the input and output of the training set as X_train and y_train respectively. Also reference the input and output of the test set as X_test and y_test respectively. Print X_train, y_train, X_test and y_test. 

In [28]:
"""
ASIDE: Printing the student_data_std dataframe. Not sure if I should be printing student_data_1
separate features from target and apply train, test, split
"""
X = student_data_std.drop(columns=['science']).copy()
y = student_data_std['science'].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=14)

In [29]:
X_train

math   reading  chocolate  strawberry  vanilla
15 -1.001191  0.811647          0           0        1
14  1.346430  0.109682          0           0        1
5  -0.034524  0.226676          1           0        0
0  -0.034524 -0.709277          0           0        1
13 -0.586905  0.460665          1           0        0
9   1.346430 -1.762225          1           0        0
7  -1.415477 -0.358295          0           0        1
6   1.346430  0.109682          0           0        1
12 -0.034524 -1.060260          0           1        0
8  -0.725001  1.279624          1           0        0
11  0.655953  1.396618          0           1        0

In [30]:
y_train

15   -1.473636
14    0.354130
5     0.536906
0     0.536906
13    0.536906
9     0.902459
7    -1.473636
6     0.719683
12   -1.108083
8    -0.376977
11   -0.925306
Name: science, dtype: float64

In [31]:
X_test

math   reading  chocolate  strawberry  vanilla
10 -1.415477  0.460665          0           0        1
3   0.655953  1.396618          0           1        0
4  -0.034524 -1.060260          0           1        0
1   1.346430 -1.762225          1           0        0
2  -1.415477  0.460665          0           0        1

In [32]:
y_test

10    1.450789
3    -0.925306
4    -1.108083
1     0.902459
2     1.450789
Name: science, dtype: float64

d) Using the boston_1 DataFrame in question 1a, select the LowTemp, HighTemp, WarmestMin, ColdestHigh, AveMin, AveMax columns and use the “pipeline” functionality in sklearn to transform the selected data using the MinMaxScalar() and Imputer() classes.  With the Imputer() class, the missing data in each column should be imputed using the mean value for the column. Assign the resulting DataFrame to a variable called pipeline_data. Print the pipeline_data

In [34]:
"""instantiate pipeline components and feed to sklearn pipeline"""
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
scaler = MinMaxScaler()
pipeline = Pipeline([('impute', imputer), ('scaler', scaler)])
pipeline

Pipeline(steps=[('impute', SimpleImputer()), ('scaler', MinMaxScaler())])

In [35]:
"""apply pipeline to select columns from boston_1 dataframe"""
pipeline_data = pipeline.fit_transform(boston_1[['LowTemp', 'HighTemp', 'WarmestMin', 'ColdestHigh',
                                                 'AveMin', 'AveMax']])
pipeline_data = pd.DataFrame(pipeline_data, columns=['LowTemp', 'HighTemp', 'WarmestMin', 'ColdestHigh',
                                                     'AveMin', 'AveMax'])
pipeline_data

LowTemp  HighTemp  WarmestMin  ColdestHigh    AveMin    AveMax
0    0.128205  0.067797    0.156863     0.126761  0.078231  0.041958
1    0.141026  0.135593    0.098039     0.183099  0.215986  0.131119
2    0.358974  0.474576    0.313725     0.309859  0.384354  0.365385
3    0.564103  0.389831    0.333333     0.478873  0.511905  0.437063
4    0.692308  0.711864    0.627451     0.591549  0.673469  0.606643
..        ...       ...         ...          ...       ...       ...
295  0.910256  0.966102    0.921569     0.929577  0.972789  1.000000
296  0.769231  0.779661    0.803922     0.788732  0.840136  0.797203
297  0.615385  0.711864    0.686275     0.591549  0.637755  0.611888
298  0.602564  0.423729    0.372549     0.450704  0.479592  0.403846
299  0.333333  0.101695    0.137255     0.239437  0.263605  0.194056

[300 rows x 6 columns]

e) Output the descriptive statistics of the pipeline_data including mean, median, variance, minimum value, maximum value, variance, standard deviation and skewness. You can use the .apply() functionality of the pandas DataFrame.

In [41]:
"""print summary statistics for pipeline_data"""
pipeline_data.agg(['mean', 'median', 'var', 'min', 'max', 'std', 'skew'])

LowTemp  HighTemp  WarmestMin  ColdestHigh    AveMin    AveMax
mean    0.603511  0.552474    0.534265     0.550014  0.594620  0.550828
median  0.609448  0.584746    0.549020     0.549655  0.586735  0.551638
var     0.062457  0.070079    0.072277     0.061260  0.068070  0.079806
min     0.000000  0.000000    0.000000     0.000000  0.000000  0.000000
max     1.000000  1.000000    1.000000     1.000000  1.000000  1.000000
std     0.249914  0.264724    0.268844     0.247507  0.260902  0.282500
skew   -0.168940 -0.356574   -0.169039    -0.067085 -0.078537 -0.079113